# Generated by Django 3.2.13 on 2022-06-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220627_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fa',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_fa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_title_fa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
