# Generated by Django 3.2.13 on 2022-06-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220624_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='max_order_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='min_order_quantity',
        ),
    ]
