# Generated by Django 3.2.13 on 2022-06-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20220627_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug_en',
            field=models.SlugField(allow_unicode=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_fa',
            field=models.SlugField(allow_unicode=True, null=True),
        ),
    ]
