# Generated by Django 3.2.13 on 2022-06-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_stock_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variant',
        ),
    ]
