# Generated by Django 3.2.13 on 2022-06-27 12:49

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('store', '0005_product_picture_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture_list',
            field=filer.fields.image.FilerImageField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='store_picture_list', to=settings.FILER_IMAGE_MODEL),
            preserve_default=False,
        ),
    ]
