# Generated by Django 3.2.13 on 2022-06-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_picture_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label_color',
            field=models.CharField(default='red', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='label_text',
            field=models.CharField(default='جدید', max_length=20),
            preserve_default=False,
        ),
    ]
