# Generated by Django 3.2.13 on 2022-06-29 17:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20220629_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fa',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='more_info',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='more_info_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='more_info_fa',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='send_and_return',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='send_and_return_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='send_and_return_fa',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
