# Generated by Django 3.2.13 on 2022-06-30 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dislike',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='like',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='خوب', max_length=100),
            preserve_default=False,
        ),
    ]
