# Generated by Django 3.2.13 on 2022-06-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20220630_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='language',
            field=models.CharField(choices=[('fa', 'پارسی'), ('en', 'English')], default='en', max_length=50),
        ),
    ]
