# Generated by Django 3.2.13 on 2022-06-30 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_review_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='picture_list',
            new_name='introductionـpicture',
        ),
    ]
