# Generated by Django 3.2.13 on 2022-06-30 11:37

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('store', '0017_rename_picture_list_product_introductionـpicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='introductionـpicture',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.PROTECT, related_name='store_picture_introduction', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
