# Generated by Django 3.2.13 on 2022-06-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_product_introductionـpicture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='introductionـpicture',
            new_name='introduction_picture',
        ),
    ]
