# Generated by Django 3.2.13 on 2022-06-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_rename_introductionـpicture_product_introduction_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
