# Generated by Django 3.2.13 on 2022-06-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_product_has_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='differentiation_value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
