# Generated by Django 3.2.14 on 2022-07-25 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_variant_differentiation_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
