# Generated by Django 3.2.14 on 2022-07-25 19:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_delete_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, default=Decimal('0.0'), max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
    ]
