# Generated by Django 3.2.14 on 2022-07-25 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
