# Generated by Django 3.2.14 on 2022-08-04 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_alter_product_minimum_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='maximum_order',
            new_name='maximum_order_quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='minimum_order',
            new_name='minimum_order_quantity',
        ),
    ]
