# Generated by Django 3.2.14 on 2022-08-06 22:38

import apps.store.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_alter_wishitem_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('expiration_date', models.DateField(default=apps.store.models.one_month_later)),
                ('minimum_purchase_amount', models.PositiveIntegerField(default=100000, verbose_name='quantity')),
                ('discount_purchase_amount', models.PositiveIntegerField(default=10000, verbose_name='quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='status_change_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_change_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status_change_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
