# Generated by Django 3.2.14 on 2022-08-07 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_alter_userprofile_email'),
        ('store', '0043_auto_20220807_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('W', 'Waiting'), ('T', 'Transferred'), ('P', 'Payed'), ('F', 'Failed')], default='W', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status_change_date', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='account.address')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.discount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Orders', to=settings.AUTH_USER_MODEL)),
                ('shipping', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.shipping')),
            ],
            options={
                'ordering': ('status_change_date',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('product_price', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name='order item')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': 'Order item',
                'verbose_name_plural': 'Order items',
                'ordering': ('id',),
            },
        ),
    ]
