# Generated by Django 3.2.13 on 2022-05-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutuspage_blogcategorypage_blogindexpage_blogslugpage_cartpage_contactuspage_contactusthankspage_h'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='brand_image')),
                ('brand_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='customer')),
                ('review', models.TextField()),
                ('customer_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='brand_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='brand_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='is_brand_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='our_mission_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='our_vision_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='picture',
            field=models.ImageField(default='', upload_to='about_us'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='who_we_are_text_1',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='who_we_are_text_2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
