# Generated by Django 3.2.13 on 2022-05-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220516_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutuspage',
            old_name='picture',
            new_name='main_picture',
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='who_we_are_picture',
            field=models.ImageField(default='', upload_to='who_we_are'),
            preserve_default=False,
        ),
    ]
