# Generated by Django 3.2.15 on 2022-08-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_brandpage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='title_en',
            field=models.CharField(default='Sepimo', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_fa',
            field=models.CharField(default='Sepimo', max_length=60, null=True),
        ),
    ]
