# Generated by Django 3.2.13 on 2022-05-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220516_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspage',
            name='customer_reviews_title',
            field=models.CharField(default='نظرات مشتری های فروشگاه', max_length=100),
        ),
    ]
