# Generated by Django 3.2.13 on 2022-05-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aboutuspage_customer_reviews_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspage',
            name='brand_title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='brand_title_fa',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
