# Generated by Django 3.2.13 on 2022-05-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220517_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspage',
            name='brand_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='brand_description_fa',
            field=models.TextField(null=True),
        ),
    ]
