# Generated by Django 3.2.13 on 2022-05-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220517_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutuspage',
            name='brand_description_en',
        ),
        migrations.RemoveField(
            model_name='aboutuspage',
            name='brand_description_fa',
        ),
        migrations.RemoveField(
            model_name='aboutuspage',
            name='brand_title_en',
        ),
        migrations.RemoveField(
            model_name='aboutuspage',
            name='brand_title_fa',
        ),
    ]
