# Generated by Django 3.2.13 on 2022-05-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220517_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspage',
            name='brand_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='brand_description_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='brand_title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='brand_title_fa',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
