# Generated by Django 3.2.13 on 2022-05-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220517_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspage',
            name='our_mission_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='our_mission_text_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='who_we_are_text_1_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='who_we_are_text_1_fa',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='who_we_are_text_2_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='who_we_are_text_2_fa',
            field=models.TextField(null=True),
        ),
    ]
