# Generated by Django 3.2.13 on 2022-05-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220517_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspage',
            name='title_en',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='title_fa',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
