# Generated by Django 3.2.13 on 2022-05-17 17:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220517_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspage',
            name='our_vision_text',
            field=tinymce.models.HTMLField(),
        ),
    ]
