# Generated by Django 3.2.13 on 2022-05-17 17:27

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_aboutuspage_our_vision_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspage',
            name='our_vision_text_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='aboutuspage',
            name='our_vision_text_fa',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
