# Generated by Django 3.2.13 on 2022-05-18 14:35

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20220517_2157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogoutPage',
        ),
        migrations.AddField(
            model_name='signuppage',
            name='background_image',
            field=models.ImageField(default='', upload_to='signup_page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='brand_description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='brand_description_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='brand_description_fa',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='our_mission_text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='our_mission_text_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='our_mission_text_fa',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='title',
            field=models.CharField(default='Sepimo', max_length=60),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='title_en',
            field=models.CharField(default='Sepimo', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='title_fa',
            field=models.CharField(default='Sepimo', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='who_we_are_text_1',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='who_we_are_text_1_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='who_we_are_text_1_fa',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='who_we_are_text_2',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='who_we_are_text_2_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='who_we_are_text_2_fa',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AlterField(
            model_name='blogcategorypage',
            name='title',
            field=models.CharField(default='Sepimo', max_length=60),
        ),
        migrations.AlterField(
            model_name='blogindexpage',
            name='title',
            field=models.CharField(default='Sepimo', max_length=60),
        ),
        migrations.AlterField(
            model_name='blogslugpage',
            name='title',
            field=models.CharField(default='Sepimo', max_length=60),
        ),
        migrations.AlterField(
            model_name='cartpage',
            name='title',
            field=models.CharField(default='Sepimo', max_length=60),
        ),
        migrations.AlterField(
            model_name='contactuspage',
            name='title',
            field=models.CharField(default='Sepimo', max_length=60),
        ),
        migrations.AlterField(
            model_name='contactusthankspage',
            name='title',
            field=models.CharField(default='Sepimo', max_length=60),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title',
            field=models.CharField(default='Sepimo', max_length=60),
        ),
        migrations.AlterField(
            model_name='loginpage',
            name='background_image',
            field=models.ImageField(upload_to='login_page'),
        ),
        migrations.AlterField(
            model_name='loginpage',
            name='title',
            field=models.CharField(default='Sepimo', max_length=60),
        ),
        migrations.AlterField(
            model_name='orderspage',
            name='title',
            field=models.CharField(default='Sepimo', max_length=60),
        ),
        migrations.AlterField(
            model_name='passwordchangedonepage',
            name='title',
            field=models.CharField(default='Sepimo', max_length=60),
        ),
        migrations.AlterField(
            model_name='passwordchangepage',
            name='title',
            field=models.CharField(default='Sepimo', max_length=60),
        ),
        migrations.AlterField(
            model_name='passwordresetcompletepage',
            name='title',
            field=models.CharField(default='Sepimo', max_length=60),
        ),
        migrations.AlterField(
            model_name='passwordresetdonepage',
            name='title',
            field=models.CharField(default='Sepimo', max_length=60),
        ),
        migrations.AlterField(
            model_name='passwordresetformpage',
            name='title',
            field=models.CharField(default='Sepimo', max_length=60),
        ),
        migrations.AlterField(
            model_name='passwordresetpage',
            name='title',
            field=models.CharField(default='Sepimo', max_length=60),
        ),
        migrations.AlterField(
            model_name='paymentpage',
            name='title',
            field=models.CharField(default='Sepimo', max_length=60),
        ),
        migrations.AlterField(
            model_name='profilepage',
            name='title',
            field=models.CharField(default='Sepimo', max_length=60),
        ),
        migrations.AlterField(
            model_name='signuppage',
            name='title',
            field=models.CharField(default='Sepimo', max_length=60),
        ),
    ]
