# Generated by Django 3.2.13 on 2022-05-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220518_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepage',
            name='header_text_background',
            field=models.ImageField(default='', upload_to='header_text_background'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilepage',
            name='header_text_big',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilepage',
            name='header_text_small',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
