# Generated by Django 3.2.13 on 2022-05-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220518_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepage',
            name='header_text_big_en',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profilepage',
            name='header_text_big_fa',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profilepage',
            name='header_text_small_en',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profilepage',
            name='header_text_small_fa',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profilepage',
            name='title_en',
            field=models.CharField(default='Sepimo', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profilepage',
            name='title_fa',
            field=models.CharField(default='Sepimo', max_length=60, null=True),
        ),
    ]
