# Generated by Django 3.2.13 on 2022-05-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20220518_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginpage',
            name='title_en',
            field=models.CharField(default='Sepimo', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='loginpage',
            name='title_fa',
            field=models.CharField(default='Sepimo', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='signuppage',
            name='title_en',
            field=models.CharField(default='Sepimo', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='signuppage',
            name='title_fa',
            field=models.CharField(default='Sepimo', max_length=60, null=True),
        ),
    ]
