# Generated by Django 3.2.13 on 2022-05-19 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('core', '0019_alter_profilepage_header_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepage',
            name='header_background2',
            field=filer.fields.image.FilerImageField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='profile_background', to=settings.FILER_IMAGE_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profilepage',
            name='header_background',
            field=models.ImageField(upload_to='profile_header_background'),
        ),
    ]
