# Generated by Django 3.2.13 on 2022-05-19 06:31

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('core', '0021_auto_20220519_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspage',
            name='who_we_are_picture',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.PROTECT, related_name='who_we_are', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='profilepage',
            name='header_background',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.PROTECT, related_name='profile_background', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
