# Generated by Django 3.2.13 on 2022-05-19 07:48

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('core', '0022_auto_20220519_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='picture',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.PROTECT, related_name='brand_image', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='customerreviews',
            name='picture',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='loginpage',
            name='background_image',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.PROTECT, related_name='login_page', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='signuppage',
            name='background_image',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.PROTECT, related_name='signup_page', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
