# Generated by Django 3.2.13 on 2022-06-17 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_passwordresetpage_background_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetCompletePage',
        ),
        migrations.DeleteModel(
            name='PasswordResetDonePage',
        ),
        migrations.DeleteModel(
            name='PasswordResetFormPage',
        ),
    ]
