# Generated by Django 3.2.13 on 2022-06-17 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20220617_1216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogCategoryPage',
        ),
        migrations.DeleteModel(
            name='BlogIndexPage',
        ),
        migrations.DeleteModel(
            name='BlogSlugPage',
        ),
    ]
