# Generated by Django 3.2.13 on 2022-06-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_signpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='signpage',
            name='title_en',
            field=models.CharField(default='Sepimo', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='signpage',
            name='title_fa',
            field=models.CharField(default='Sepimo', max_length=60, null=True),
        ),
    ]
