# Generated by Django 3.2.13 on 2022-06-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20220617_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetpage',
            name='title_en',
            field=models.CharField(default='Sepimo', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetpage',
            name='title_fa',
            field=models.CharField(default='Sepimo', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profilepage',
            name='menu_password_change',
            field=models.CharField(default='تغییر گذرواژه', max_length=60),
        ),
    ]
