# Generated by Django 3.2.13 on 2022-06-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20220617_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepage',
            name='menu_password_change_en',
            field=models.CharField(default='تغییر گذرواژه', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='profilepage',
            name='menu_password_change_fa',
            field=models.CharField(default='تغییر گذرواژه', max_length=60, null=True),
        ),
    ]
