# Generated by Django 3.2.13 on 2022-06-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20220617_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='signpage',
            name='text_head',
            field=models.CharField(default='did you forget your password?', max_length=200),
        ),
        migrations.AddField(
            model_name='signpage',
            name='text_help',
            field=models.CharField(default='enter your email to reset your password', max_length=200),
        ),
    ]
