# Generated by Django 3.2.13 on 2022-06-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20220617_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signpage',
            name='text_head',
        ),
        migrations.RemoveField(
            model_name='signpage',
            name='text_help',
        ),
        migrations.AddField(
            model_name='passwordresetpage',
            name='text_head',
            field=models.CharField(default='did you forget your password?', max_length=200),
        ),
        migrations.AddField(
            model_name='passwordresetpage',
            name='text_head_en',
            field=models.CharField(default='did you forget your password?', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetpage',
            name='text_head_fa',
            field=models.CharField(default='did you forget your password?', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetpage',
            name='text_help',
            field=models.CharField(default='enter your email to reset your password', max_length=200),
        ),
        migrations.AddField(
            model_name='passwordresetpage',
            name='text_help_en',
            field=models.CharField(default='enter your email to reset your password', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetpage',
            name='text_help_fa',
            field=models.CharField(default='enter your email to reset your password', max_length=200, null=True),
        ),
    ]
