# Generated by Django 3.2.13 on 2022-06-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20220617_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetpage',
            name='password_sent_message',
            field=models.TextField(default="We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly. If you don't receive an email, please make sure you've entered the address you registered with,and check your spam folder.", max_length=300),
        ),
        migrations.AlterField(
            model_name='passwordresetpage',
            name='password_sent_message_en',
            field=models.TextField(default="We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly. If you don't receive an email, please make sure you've entered the address you registered with,and check your spam folder.", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetpage',
            name='password_sent_message_fa',
            field=models.TextField(default="We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly. If you don't receive an email, please make sure you've entered the address you registered with,and check your spam folder.", max_length=300, null=True),
        ),
    ]
