# Generated by Django 3.2.13 on 2022-06-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20220617_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='about_blog_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='about_blog_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='about_blog_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
