# Generated by Django 3.2.13 on 2022-06-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20220621_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='about_blog_text',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
