# Generated by Django 3.2.13 on 2022-06-24 20:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import mptt.fields
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('name_fa', models.CharField(max_length=50, null=True, unique=True)),
                ('name_en', models.CharField(max_length=50, null=True, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.category')),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_fa', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('intro', tinymce.models.HTMLField()),
                ('intro_fa', tinymce.models.HTMLField(null=True)),
                ('intro_en', tinymce.models.HTMLField(null=True)),
                ('content', tinymce.models.HTMLField()),
                ('content_fa', tinymce.models.HTMLField(null=True)),
                ('content_en', tinymce.models.HTMLField(null=True)),
                ('content2', tinymce.models.HTMLField()),
                ('content2_fa', tinymce.models.HTMLField(null=True)),
                ('content2_en', tinymce.models.HTMLField(null=True)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Trash', 'Trash')], max_length=50)),
                ('view', models.BigIntegerField(blank=True, default=0, null=True)),
                ('pub_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category')),
                ('intro_picture', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.PROTECT, related_name='blog_intro', to=settings.FILER_IMAGE_MODEL)),
                ('picture_content', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.PROTECT, related_name='blog_content', to=settings.FILER_IMAGE_MODEL)),
                ('picture_header', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.PROTECT, related_name='blog_header', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
            },
        ),
        migrations.CreateModel(
            name='PostViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Visit Date')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Trash', 'Trash')], default='Draft', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField(max_length=1000)),
                ('replay', models.TextField(blank=True, max_length=1000, null=True)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
