# Generated by Django 3.2.13 on 2022-06-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220519_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='intro_picture_text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='picture_content_text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='picture_header_text',
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fa',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_fa',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
