# Generated by Django 3.2.13 on 2022-06-17 15:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220617_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content2_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content2_fa',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_fa',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='intro_en',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='intro_fa',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
