# Generated by Django 3.2.13 on 2022-06-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postviewhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replay',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Trash', 'Trash')], default='Draft', max_length=10),
        ),
    ]
