# Generated by Django 3.2.13 on 2022-05-23 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userprofile_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=30, verbose_name='state')),
                ('city', models.CharField(max_length=30, verbose_name='city')),
                ('area', models.CharField(max_length=2, verbose_name='area')),
                ('postal_code', models.CharField(max_length=11, verbose_name='city')),
                ('address', models.TextField(max_length=300, verbose_name='address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
