# Generated by Django 3.2.13 on 2022-06-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20220613_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='provence',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(default='', max_length=30, verbose_name='\novince'),
            preserve_default=False,
        ),
    ]
